### ISSUE TITLE
run should not crash when resource is not available

### ISSUE THREAD

**Issue by rezib** [edf-hpc/unclebench#1]
This stacktrace happens when `run` is used before `fetch`, and it should be avoided:

```
rp140c6n@athos1:~$ ubench run -b vasp -p athos

---- Copying /usr/share/unclebench/benchmarks/vasp to /scratch/rp140c6n/Ubench/benchmarks/vasp

Traceback (most recent call last):
  File "/usr/bin/ubench", line 83, in <module>
    run.run(platform=args.p,benchmark_list=args.b,w_list=args.w)
  File "/usr/share/unclebench/lib/run.py", line 86, in run
    if not (benchmark_name in os.listdir(ph.resource_dir)):
OSError: [Errno 2] No such file or directory: '/scratch/rp140c6n/Ubench/resource'
```

**Comment by pierretr** [comment]
Fixed with commit 35139c954cc6ffa726fed5c382e5ce742d250f74
