### ISSUE TITLE
result crash when there is no result to read

### ISSUE THREAD

**Issue by rezib** [edf-hpc/unclebench#3]
The `result` comands crashes with the following stacktrace when there is no result to read:

```
rp140c6n@athos1:~$ ubench result -b stream
Processing stream benchmark :
----analysing results
Traceback (most recent call last):
  File "/usr/bin/ubench", line 87, in <module>
    result.result(benchmark_list=args.b)
  File "/usr/share/unclebench/lib/result.py", line 77, in result
    bm.analyse_last_benchmark()
  File "/usr/share/unclebench/lib/benchmark_managers/benchmark_manager.py", line 153, in analyse_last_benchmark
    self.benchmark_results_path=self.ibenchmark_manager.analyse_last_benchmark()
  File "/usr/share/unclebench/lib/benchmark_managers/jube_ibenchmark_manager.py", line 78, in analyse_last_benchmark
    return self.analyse_benchmark('last')
  File "/usr/share/unclebench/lib/benchmark_managers/jube_ibenchmark_manager.py", line 55, in analyse_benchmark
    os.chdir(self.benchmark_path)
OSError: [Errno 2] No such file or directory: '/scratch/rp140c6n/Ubench/benchmarks/stream'
```

It should fail more nicely.

**Comment by pierretr** [comment]
Fixed with commit 818c558dc6aaba5beb285e61c1c189373488158c
